name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
# prerelease-identifier: 'alpha' # alpha, beta, rc
# prerelease: true
# filter-by-commitish: true
# commitish: v1.x

categories:
  - title: 'Dependency Updates'
    label: 'dependencies'
    collapse-after: 5

version-resolver:
  major:
    labels:
      - 'breaking change'
      - 'removed'
  minor:
    labels:
      - 'feature'
  default: patch

autolabeler:
  - label: 'breaking change'
    title:
      - '/new:/i'
  - label: 'feature'
    title:
      - '/added:/i'
  - label: 'changed'
    title:
      - '/changed:/i'
  - label: 'deprecated'
    title:
      - '/deprecated:/i'
  - label: 'removed'
    title:
      - '/removed:/i'
  - label: 'fixed'
    title:
      - '/fixed:/i'
  - label: 'security'
    title:
      - '/security:/i'
  - label: 'dependencies'
    title:
      - '/dependencies:/i'
  - label: 'documentation'
    title:
      - '/docs:/i'

template: |

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
