name: Release

on:
  release:
    types:
      - released

jobs:
  update:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@buddywinangun'

      - name: npm publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
