name: Automatic Release
run-name: ${{ github.actor }} is automatically releasing

on: push

permissions:
  contents: read

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
      id-token: write

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Checking out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setting up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@buddywinangun'

      - name: Installing dependencies
        run: pnpm install

      - name: Releasing via Semantic Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ steps.generate-token.outputs.token }}
